# add_keyword.sh !/bin/bash

/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Website_name/new_website.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Website_name/teach_web.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Website_name/video_web.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Website_name/estate_website.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Website_name/website_dictionary.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Misc/profession.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Misc/leaders_name.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Misc/country_name.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Location_name/city.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Location_name/guangdong.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Location_name/china_place.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/finance_org.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/fiber_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/consult_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/flax_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/printing_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/govenment_org.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/company_name.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/foregin_investment.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/wiring_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/spinning_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/leather_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/cloths_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/toy_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/sheep_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/children_gar_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/handiword_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/down_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/jewelry_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/shoes_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/gift_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/makeup_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Organization_name/silk_company.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Stock_name/stock_name.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Stock_name/ss_stock.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Stock_name/A_share_name.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Stock_name/new_stock_2014.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Stock_name/A_share_simple.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Insurance/insurance.scel
/MuseSp/bin/mkdic --add noun scel 1 /MuseSp/dict/scel/Noun/Future_goods/future_goods.scel
